spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cloud_transfer
    username: dhaval
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        enable_lazy_load_no_trans: true
        type: trace
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true